### ISSUE TITLE
Discord::updatePresence() not working

### ISSUE THREAD

**Issue by Kygekraqmak** [teamreflex/DiscordPHP#325]
I don't know is this a bug or I configured it wrong, but why `Discord::updatePresence()` is not working with my Discord bot? I want to set the status but it didn't worked. So what's the issue?

**Any help would be appreciated!**

**NOTE:** Code is available below. Just extract the archive to open the code. The `commands()` function is working. I've replaced the token to `<TOKEN>` for privacy reasons.

Code ---> [Code.zip](https://github.com/teamreflex/DiscordPHP/files/5259643/Code.zip)

**Comment by oliverschloebe** [comment]
The `Game` class has been replaced with `Activity`. See [here](https://github.com/teamreflex/DiscordPHP/issues/301#issuecomment-681059219) for a working example.

Please not that setting a custom status is [not allowed for bots](https://github.com/teamreflex/DiscordPHP/issues/312#issuecomment-694923315).

**Comment by Kygekraqmak** [comment]
Why there's no `Activity::TYPE_WATCHING`?

Discord\Parts\User\Activity.php:
```php
    const TYPE_PLAYING = 0; // Playing {$this->name}
    const TYPE_STREAMING = 1; // Streaming {$this->details}
    const TYPE_LISTENING = 2; // Listening to {$this->name}
    const TYPE_CUSTOM = 4; // {$this->emoji} {$this->name}
```

**Comment by davidcole1340** [comment]
Discord doesn't have a watching activity type: https://discord.com/developers/docs/topics/gateway#activity-object-activity-types

**Comment by Kygekraqmak** [comment]
> The `Game` class has been replaced with `Activity`. See [here](https://github.com/teamreflex/DiscordPHP/issues/301#issuecomment-681059219) for a working example.
> 
> Please note that setting a custom status is [not allowed for bots](https://github.com/teamreflex/DiscordPHP/issues/312#issuecomment-694923315).

I've used it but it looks like still not working.

New Code ---> [Code.zip](https://github.com/teamreflex/DiscordPHP/files/5260491/Code.zip)

**Comment by davidcole1340** [comment]
```php
$discord->on('ready', function($discord) {
    $activity = $discord->factory(\Discord\Parts\User\Activity::class, [
        'name' => '&help',
        'type' => Activity::TYPE_LISTENING
    ]);
    $discord->updatePresence($activity);
});
```
You need to import the `Activity` class when you set the type, or use the full namespace:

```php
use Discord\Parts\User\Activity; // at the top of the file, under the import

$discord->on('ready', function($discord) {
    $activity = $discord->factory(Activity::class, [
        'name' => '&help',
        'type' => Activity::TYPE_LISTENING
    ]);
    $discord->updatePresence($activity);
});
```

**Comment by Kygekraqmak** [comment]
Still not showing "Listening &help"

**Comment by xxAROX** [comment]
try this:
```php
		/** @var Activity $activity */
		$activity = $this->factory(Activity::class);
		$activity->name = "&help";
		$activity->type = Activity::TYPE_LISTENING;
		$this->updatePresence($activity, false, "online", false);
```
@Kygekraqmak

**Comment by Kygekraqmak** [comment]
@xxAROX 

I've tried to use your code, but it throws an error (cannot assign $activity->name and $activity->type).
So I changed to this:

```php
$activity = $discord->factory(Activity::class, [
        'name' => '&help',
        'type' => Activity::TYPE_LISTENING
    ]);
    $discord->updatePresence($activity, false, "online", false);
```

But still nothing happened.
So what's the problem?

**Comment by davidcole1340** [comment]
@Kygekraqmak have you included the `Activity` class?

**Comment by Ravisdo** [comment]
For me, the code works
```
use Discord\Parts\User\Activity;

            $activity = $this->client->factory(Activity::class, [
                'name' => '&help',
                'type' => Activity::TYPE_LISTENING
            ]);
            $this->client->updatePresence($activity, false, "online", false);
```
![bot](https://user-images.githubusercontent.com/16488305/94365694-3c9db500-00d3-11eb-8f1a-e18bf541d5f5.PNG)

**Comment by Ravisdo** [comment]
The problem seems to be in your code, you try to create two instances of your bot.
That wil not work.

You must only create one bot instance and use this inb your functions

```
<?php

include __DIR__.'/vendor/autoload.php';

use Discord\DiscordCommandClient as Commands;
use Discord\Parts\User\Activity;

$discordCommandClient = new Commands([
    'token' => '<TOKEN>',
    'prefix' => '&',
    'name' => 'StayWait Bot',
    'description' => 'Bot resmi server Discord StayWait Network'
]);

function commands($command) {

    $command->registerCommand('test', 'Kalau ini muncul berarti bot nya work!', [
        'description' => 'Tes bot server Discord StayWait'
    ]);
    $command->registerCommand('vote', 'Link vote: https://r.staywait.xyz/vote', [
        'aliases' => ['linkvote', 'v', 'linkv'],
        'description' => 'Link vote server StayWait'
    ]);
    $command->registerCommand('about', '**Bot Server Discord StayWait**\nDibuat oleh Kygekraqmak menggunakan bahasa pemrograman PHP.', [
        'description' => 'Tentang bot server Discord StayWait'
    ]);

    $command->run();
}

function status($discordCommandClient) {
    $activity = $discordCommandClient->factory(Activity::class, [
        'name' => '&help',
        'type' => Activity::TYPE_LISTENING
    ]);

    $discordCommandClient->updatePresence($activity);
}

commands($discordCommandClient);
status($discordCommandClient);
```

**Comment by Kygekraqmak** [comment]
Thanks a lot!

Last question: How to remove user mention on command?

**Comment by Ravisdo** [comment]
1.
```
        $this->client->registerCommand('test', function (Message $message, array $arguments) {
            if ($message->author->id === $this->client->id) {
                return;
            }
            $replyMessage = 'Here is a reply to the command "!test"';
            if (count($arguments) > 0) {
                $replyMessage .= PHP_EOL . 'Arguments are: ' . implode(', ', $arguments);
            }
            $message->channel->sendMessage($replyMessage);
        }, [
            'description' => 'Test a command',
            'usage' => '!test [maybe] [some] [arguments]',
            'longDescription' => 'Here could be stand a even longer description for the "test" command.',
        ]);
```
2. The status may be stand "forever". You could update the status as long as the bot is online with a command.

3.
You can write an own help command and disable the default hellp with following option on the initlialization on the bot
`'defaultHelpCommand' => false` => https://discordphp.readme.io/docs/command-client
Than you must write the command itself with some internal loops i guess to get all commands with its description.

Take a look at https://github.com/teamreflex/DiscordPHP/blob/e65f063c5cf19481818be412c94e85bbf2378549/src/Discord/DiscordCommandClient.php#L91

**Comment by Kygekraqmak** [comment]
I've changed the bot status so it displays the amount of players in a game server (the function is getPlayers()). If I want the bot to update the status every 60 seconds, should I use this?

```php
function status($discordCommandClient) {
    $discordCommandClient->on('ready', function ($discord) {
        $activity = $discord->factory(Activity::class, [
            'name' => getPlayers() . ' players',
            'type' => Activity::TYPE_LISTENING
        ]);
        try {
            while (true) {
                $discord->updatePresence($activity);
                sleep(60);
            }
        } catch (\Exception $exception) {
            echo $exception->getMessage() . PHP_EOL;
        }
    });
}
```

**Comment by oliverschloebe** [comment]
Havn't tested this myself, but this should be working:
```php
$activity = $discord->factory(Activity::class, [
	'name' => getPlayers() . ' players',
	'type' => Activity::TYPE_LISTENING
]);
$discord->getLoop()->addPeriodicTimer(60, function() use ($discord, $activity) {
	$discord->updatePresence($activity);
});
```

**Comment by Ravisdo** [comment]
I think the problem is solved here und the issue can be closed, right @Kygekraqmak ?

**Comment by Kygekraqmak** [comment]
> You can write an own help command and disable the default hellp with following option on the initlialization on the bot
> `'defaultHelpCommand' => false` => https://discordphp.readme.io/docs/command-client
> Than you must write the command itself with some internal loops i guess to get all commands with its description.
> 
> Take a look at
> 
> https://github.com/teamreflex/DiscordPHP/blob/e65f063c5cf19481818be412c94e85bbf2378549/src/Discord/DiscordCommandClient.php#L91

No, I mean how to display a close-able embed message, for example:

![image](https://user-images.githubusercontent.com/68368066/94669541-f4d19480-0343-11eb-8d4e-ae006123f7f6.png)

> Havn't tested this myself, but this should be working:
> 
> ```
> $activity = $discord->factory(Activity::class, [
> 	'name' => getPlayers() . ' players',
> 	'type' => Activity::TYPE_LISTENING
> ]);
> $discord->getLoop()->addPeriodicTimer(60, function() use ($discord, $activity) {
> 	$discord->updatePresence($activity);
> });
> ```

This doesn't worked. The status doesn't get updated.

> I think the problem is solved here und the issue can be closed, right @Kygekraqmak ?

The main issue (Discord::updatePresence()) is already solved, but I still have some questions. Maybe share a link of Discord server?

**Comment by davidcole1340** [comment]
Feel free to join us here: https://discord.com/invite/0duG4FF1ElFGUFVq

**Comment by davidcole1340** [comment]
Closing this due to age, if you have any more issues join the server above and we can give you a hand.
